# Generated by Django 4.2.3 on 2023-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationimages',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='medicationimages',
            name='front_image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='medicationimages',
            name='package_image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
