# Generated by Django 4.2.3 on 2023-07-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_medicationimages_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativemedications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicationimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicationimages',
            name='medication_strength',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.medicationstrength'),
        ),
        migrations.AlterField(
            model_name='medicationinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicationstrength',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
